import { Empleado } from './types';

export const EMPLEADOS_MOCK: Empleado[] = [
  {
    id: 'EMP-001',
    nif: '48920112A',
    nombre: 'Carlos',
    apellidos: 'Mendoza Díaz',
    email: 'carlos.mendoza@gestarian-taller.es',
    telefono: '+34 611 223 344',
    direccion: 'Av. de América 24, 3ºB, Madrid',
    grupoCotizacion: 3, // Jefes Administrativos y de Taller
    puesto: 'Jefe de Taller Mecánico',
    epigrafeActividad: 'IAE 691.2 - Reparación y Mantenimiento de Vehículos (Grupo 3 TGSS)',
    rolPlataforma: 'RESPONSABLE',
    permisos: ['Control Horario', 'Gestión de Fichajes', 'Supervisión de Taller', 'Emisión de Partes'],
    cnaeEmpresa: '4520 - Mantenimiento y reparación de vehículos de motor',
    convenioColectivo: 'Convenio Provincial del Metal y Talleres de Reparación',
    tipoContrato: 'INDEFINIDO',
    jornada: 'COMPLETA',
    horasMensuales: 160,
    controlHorarioActivo: true,
    horasRegistradasMes: 160,
    fechaInicioContrato: '2022-03-01',
    salarioBaseMensual: 2200.00,
    complementosSalariales: 300.00,
    devengosNoSalariales: 80.00,
    porcentajeIrpf: 15.0,
    prorrateoPagasExtras: true
  },
  {
    id: 'EMP-002',
    nif: '52309144B',
    nombre: 'Laura',
    apellidos: 'Ramos Vega',
    email: 'laura.ramos@gestarian-taller.es',
    telefono: '+34 622 334 455',
    direccion: 'Calle Alcalá 112, 1ºA, Madrid',
    grupoCotizacion: 5, // Oficiales Administrativos
    puesto: 'Responsable de Facturación y Atención al Cliente',
    epigrafeActividad: 'IAE 844 - Servicios de Facturación y Gestión Contable (Grupo 5 TGSS)',
    rolPlataforma: 'CONTABLE',
    permisos: ['Facturación', 'Cobros', 'Nóminas', 'Descarga Informes Gestoría A3/Sage'],
    cnaeEmpresa: '4520 - Mantenimiento y reparación de vehículos de motor',
    convenioColectivo: 'Convenio Provincial del Metal y Talleres de Reparación',
    tipoContrato: 'INDEFINIDO',
    jornada: 'COMPLETA',
    horasMensuales: 160,
    controlHorarioActivo: true,
    horasRegistradasMes: 158.5,
    fechaInicioContrato: '2023-09-15',
    salarioBaseMensual: 1650.00,
    complementosSalariales: 150.00,
    devengosNoSalariales: 40.00,
    porcentajeIrpf: 12.0,
    prorrateoPagasExtras: true
  },
  {
    id: 'EMP-003',
    nif: '76110928C',
    nombre: 'Alejandro',
    apellidos: 'Gil Soto',
    email: 'alejandro.gil@gestarian-taller.es',
    telefono: '+34 633 445 566',
    direccion: 'Paseo de la Castellana 204, Madrid',
    grupoCotizacion: 8, // Oficiales de primera y segunda
    puesto: 'Mecánico Especialista en Electricidad e Híbridos',
    epigrafeActividad: 'IAE 691.2 - Electromecánica y Diagnosis (Grupo 8 TGSS)',
    rolPlataforma: 'EMPLEADO',
    permisos: ['Fichaje de Jornada', 'Consulta de Nóminas Propias'],
    cnaeEmpresa: '4520 - Mantenimiento y reparación de vehículos de motor',
    convenioColectivo: 'Convenio Provincial del Metal y Talleres de Reparación',
    tipoContrato: 'TEMPORAL',
    jornada: 'PARCIAL',
    horasMensuales: 80,
    controlHorarioActivo: true,
    horasRegistradasMes: 78,
    fechaInicioContrato: '2026-05-01',
    fechaFinContrato: '2026-10-31',
    periodoPruebaFin: '2026-07-01',
    salarioBaseMensual: 1800.00,
    complementosSalariales: 200.00,
    devengosNoSalariales: 60.00,
    porcentajeIrpf: 13.5,
    prorrateoPagasExtras: true
  }
];
